name: Avtomated tests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: all
        options:
        - all
        - smoke
        

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirment.txt
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest  
